version: '3.9'

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_omni
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-omni_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-omni_password}
      POSTGRES_DB: ${DATABASE_DB:-omni_db}
      TZ: 'America/Sao_Paulo'
      PGTZ: 'America/Sao_Paulo'
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DATABASE_USER:-omni_user} -d ${DATABASE_DB:-omni_db}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2g

  redis:
    image: redis:7-alpine
    container_name: redis_omni
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '${DATABASE_REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    environment:
      TZ: 'America/Sao_Paulo'
    healthcheck:
      test:
        [
          'CMD',
          'redis-cli',
          '-h',
          '${DATABASE_REDIS_HOST:-localhost}',
          '-p',
          '${DATABASE_REDIS_PORT:-6379}',
          'ping',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2g

volumes:
  postgres_data:
  redis_data:
